services:
  db:
    image: postgres:16-alpine
    container_name: data_base
    environment:
      POSTGRES_DB: fileProcessor_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fileprocessor_backend
    environment:
      - ConnectionStrings__PostgresConnection=Host=db;Database=fileProcessor_db;Username=admin;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fileprocessor-frontend-web
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  data:
