services:
  db:
    image: postgres:16-alpine
    container_name: data_base
    environment:
      POSTGRES_DB: fileProcessor_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
