// <auto-generated />
using System;
using FileProcessor.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileProcessor.Infra.Migrations
{
    [DbContext(typeof(FileProcessorDbContext))]
    [Migration("20250831133121_InitialLayoutSchema")]
    partial class InitialLayoutSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileProcessor.Domain.Entities.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcquirerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Identifier")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.ToTable("Layouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e79206b-3a83-42e6-8e8e-1b3c2e1f4d9b"),
                            AcquirerName = "UfCard",
                            Identifier = '0'
                        },
                        new
                        {
                            Id = new Guid("8a6b1e3c-1b9d-4e2a-9f8c-3d4a5b6c7d8e"),
                            AcquirerName = "FagammonCard",
                            Identifier = '1'
                        });
                });

            modelBuilder.Entity("FileProcessor.Domain.Entities.LayoutField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitPosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("LayoutFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1b2a3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6"),
                            DataType = "NUM",
                            InitPosition = 2,
                            LayoutId = new Guid("4e79206b-3a83-42e6-8e8e-1b3c2e1f4d9b"),
                            Length = 10,
                            Name = "Estabelecimento"
                        },
                        new
                        {
                            Id = new Guid("d2c3b4e5-f6a7-b8c9-d0e1-f2a3b4c5d6e7"),
                            DataType = "DATE_YYYYMMDD",
                            InitPosition = 12,
                            LayoutId = new Guid("4e79206b-3a83-42e6-8e8e-1b3c2e1f4d9b"),
                            Length = 8,
                            Name = "DataProcessamento"
                        },
                        new
                        {
                            Id = new Guid("e3d4c5f6-a7b8-c9d0-e1f2-a3b4c5d6e7f8"),
                            DataType = "DATE_YYYYMMDD",
                            InitPosition = 20,
                            LayoutId = new Guid("4e79206b-3a83-42e6-8e8e-1b3c2e1f4d9b"),
                            Length = 8,
                            Name = "PeriodoInicial"
                        },
                        new
                        {
                            Id = new Guid("f4e5d6a7-b8c9-d0e1-f2a3-b4c5d6e7f8a9"),
                            DataType = "DATE_YYYYMMDD",
                            InitPosition = 28,
                            LayoutId = new Guid("4e79206b-3a83-42e6-8e8e-1b3c2e1f4d9b"),
                            Length = 8,
                            Name = "PeriodoFinal"
                        },
                        new
                        {
                            Id = new Guid("a5f6e7b8-c9d0-e1f2-a3b4-c5d6e7f8a9b0"),
                            DataType = "NUM",
                            InitPosition = 36,
                            LayoutId = new Guid("4e79206b-3a83-42e6-8e8e-1b3c2e1f4d9b"),
                            Length = 7,
                            Name = "Sequencia"
                        },
                        new
                        {
                            Id = new Guid("b6a7f8c9-d0e1-f2a3-b4c5-d6e7f8a9b0c1"),
                            DataType = "DATE_YYYYMMDD",
                            InitPosition = 2,
                            LayoutId = new Guid("8a6b1e3c-1b9d-4e2a-9f8c-3d4a5b6c7d8e"),
                            Length = 8,
                            Name = "DataProcessamento"
                        },
                        new
                        {
                            Id = new Guid("c7b8a9d0-e1f2-a3b4-c5d6-e7f8a9b0c1d2"),
                            DataType = "NUM",
                            InitPosition = 10,
                            LayoutId = new Guid("8a6b1e3c-1b9d-4e2a-9f8c-3d4a5b6c7d8e"),
                            Length = 8,
                            Name = "Estabelecimento"
                        },
                        new
                        {
                            Id = new Guid("d8c9b0e1-f2a3-b4c5-d6e7-f8a9b0c1d2e3"),
                            DataType = "NUM",
                            InitPosition = 30,
                            LayoutId = new Guid("8a6b1e3c-1b9d-4e2a-9f8c-3d4a5b6c7d8e"),
                            Length = 7,
                            Name = "Sequencia"
                        });
                });

            modelBuilder.Entity("FileProcessor.Domain.Entities.LayoutField", b =>
                {
                    b.HasOne("FileProcessor.Domain.Entities.Layout", "Layout")
                        .WithMany("Fields")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("FileProcessor.Domain.Entities.Layout", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
